In [33]:
import pandas as pd

In [34]:
dt = pd.read_excel('7 - ComercialPrime_300_Registros.xlsx')

In [35]:
dt

,ID_Registro,Data_Pedido,Numero_Pedido,Cliente,Cidade_Cliente,Estado,Vendedor,Produto,Categoria,Quantidade,Valor_Unitario,Valor_Total,Nota_Satisfacao,Comentario_Satisfacao,Forma_Pagamento,Observacao
0,1,2025-02-28,PED-1001,Construtora PR,Cascavel,PR,Carlos S.,Soldadora,Medição,9,4165.28,37487.52,10,Muito Satisfeito,Boleto,NaN
1,2,2025-01-30,PED-1002,Cliente XPTO,Maringá,PR,Carlos S.,Parafusadeira,Ferramentas,28,3713.18,103969.04,10,Muito Satisfeito,PIX,NaN
2,3,2025-05-09,PED-1003,Cliente XPTO,Araucária,PR,Carlos S.,Soldadora,Soldagem,12,3067.67,36812.04,10,Muito Satisfeito,Boleto,NaN
3,4,2025-05-21,PED-1004,Construtora PR,Ponta Grossa,PR,Carlos S.,Parafusadeira,Ferramentas,9,1130.22,10171.98,0,Muito Insatisfeito,Cartão,NaN
4,5,2025-03-23,PED-1005,Construtora PR,Maringá,PR,Carlos S.,Parafusadeira,Soldagem,4,2794.73,11178.92,10,Muito Satisfeito,Boleto,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,2025-03-29,PED-1296,Loja Ferramentas BR,Curitiba,PR,Carlos S.,Furadeira,Elétrica,14,1543.26,21605.64,0,Muito Insatisfeito,Cartão,NaN
296,297,2025-03-13,PED-1297,Construtora PR,Cascavel,PR,Carlos S.,Soldadora,Elétrica,2,642.54,1285.08,6,Neutro,Boleto,NaN
297,298,2025-05-11,PED-1298,Oficina Curitiba,Maringá,PR,Carlos S.,Parafusadeira,Elétrica,2,3353.80,6707.60,10,Muito Satisfeito,Cartão,NaN
298,299,2025-03-17,PED-1299,Mercado Industrial,Curitiba,PR,Carlos S.,Parafusadeira,Elétrica,1,1554.33,1554.33,6,Neutro,Boleto,NaN
299,300,2025-03-09,PED-1300,Cliente XPTO,Ponta Grossa,PR,Carlos S.,Parafusadeira,Medição,7,3172.19,22205.33,0,Muito Insatisfeito,PIX,NaN

In [36]:
sorted(dt['Cidade_Cliente'].unique())

['Araucária', 'Cascavel', 'Curitiba', 'Londrina', 'Maringá', 'Ponta Grossa']

In [38]:
sorted(dt['Comentario_Satisfacao'].unique())

['Muito Insatisfeito', 'Muito Satisfeito', 'Neutro']

In [42]:
dt['Produto'].unique()

<StringArray>
['Soldadora', 'Parafusadeira', 'Furadeira']
Length: 3, dtype: str

In [48]:
media = dt.loc[dt["Produto"] == "Parafusadeira", "Valor_Unitario"].mean()
media

np.float64(2456.845684210526)

In [49]:
dt.loc[dt["Produto"] == "Parafusadeira", "Valor_Unitario"] = media

In [50]:
dt.loc[dt["Produto"] == "Parafusadeira"]

,ID_Registro,Data_Pedido,Numero_Pedido,Cliente,Cidade_Cliente,Estado,Vendedor,Produto,Categoria,Quantidade,Valor_Unitario,Valor_Total,Nota_Satisfacao,Comentario_Satisfacao,Forma_Pagamento,Observacao
1,2,2025-01-30,PED-1002,Cliente XPTO,Maringá,PR,Carlos S.,Parafusadeira,Ferramentas,28,2456.845684,103969.04,10,Muito Satisfeito,PIX,NaN
3,4,2025-05-21,PED-1004,Construtora PR,Ponta Grossa,PR,Carlos S.,Parafusadeira,Ferramentas,9,2456.845684,10171.98,0,Muito Insatisfeito,Cartão,NaN
4,5,2025-03-23,PED-1005,Construtora PR,Maringá,PR,Carlos S.,Parafusadeira,Soldagem,4,2456.845684,11178.92,10,Muito Satisfeito,Boleto,NaN
5,6,2025-06-28,PED-1006,Construtora PR,Cascavel,PR,Carlos S.,Parafusadeira,Elétrica,21,2456.845684,69965.28,6,Neutro,Cartão,NaN
7,8,2025-03-13,PED-1008,Construtora PR,Londrina,PR,Carlos S.,Parafusadeira,Elétrica,6,2456.845684,4398.12,6,Neutro,Cartão,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,293,2025-01-24,PED-1293,Indústria Alpha,Cascavel,PR,Carlos S.,Parafusadeira,Medição,12,2456.845684,31052.04,0,Muito Insatisfeito,Boleto,NaN
294,295,2025-03-22,PED-1295,Metalúrgica Sul,Araucária,PR,Carlos S.,Parafusadeira,Medição,12,2456.845684,34913.16,0,Muito Insatisfeito,PIX,NaN
297,298,2025-05-11,PED-1298,Oficina Curitiba,Maringá,PR,Carlos S.,Parafusadeira,Elétrica,2,2456.845684,6707.60,10,Muito Satisfeito,Cartão,NaN
298,299,2025-03-17,PED-1299,Mercado Industrial,Curitiba,PR,Carlos S.,Parafusadeira,Elétrica,1,2456.845684,1554.33,6,Neutro,Boleto,NaN
299,300,2025-03-09,PED-1300,Cliente XPTO,Ponta Grossa,PR,Carlos S.,Parafusadeira,Medição,7,2456.845684,22205.33,0,Muito Insatisfeito,PIX,NaN

In [77]:
dt["Valor_Total"] = dt["Quantidade"] * dt["Valor_Unitario"]

In [58]:
dt.loc[dt["Produto"] == "Parafusadeira"]

,ID_Registro,Data_Pedido,Numero_Pedido,Cliente,Cidade_Cliente,Estado,Vendedor,Produto,Categoria,Quantidade,Valor_Unitario,Valor_Total,Nota_Satisfacao,Comentario_Satisfacao,Forma_Pagamento,Observacao
1,2,2025-01-30,PED-1002,Cliente XPTO,Maringá,PR,Carlos S.,Parafusadeira,Ferramentas,28,2456.845684,68791.679158,10,Muito Satisfeito,PIX,NaN
3,4,2025-05-21,PED-1004,Construtora PR,Ponta Grossa,PR,Carlos S.,Parafusadeira,Ferramentas,9,2456.845684,22111.611158,0,Muito Insatisfeito,Cartão,NaN
4,5,2025-03-23,PED-1005,Construtora PR,Maringá,PR,Carlos S.,Parafusadeira,Ferramentas,4,2456.845684,9827.382737,10,Muito Satisfeito,Boleto,NaN
5,6,2025-06-28,PED-1006,Construtora PR,Cascavel,PR,Carlos S.,Parafusadeira,Ferramentas,21,2456.845684,51593.759368,6,Neutro,Cartão,NaN
7,8,2025-03-13,PED-1008,Construtora PR,Londrina,PR,Carlos S.,Parafusadeira,Ferramentas,6,2456.845684,14741.074105,6,Neutro,Cartão,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,293,2025-01-24,PED-1293,Indústria Alpha,Cascavel,PR,Carlos S.,Parafusadeira,Ferramentas,12,2456.845684,29482.148211,0,Muito Insatisfeito,Boleto,NaN
294,295,2025-03-22,PED-1295,Metalúrgica Sul,Araucária,PR,Carlos S.,Parafusadeira,Ferramentas,12,2456.845684,29482.148211,0,Muito Insatisfeito,PIX,NaN
297,298,2025-05-11,PED-1298,Oficina Curitiba,Maringá,PR,Carlos S.,Parafusadeira,Ferramentas,2,2456.845684,4913.691368,10,Muito Satisfeito,Cartão,NaN
298,299,2025-03-17,PED-1299,Mercado Industrial,Curitiba,PR,Carlos S.,Parafusadeira,Ferramentas,1,2456.845684,2456.845684,6,Neutro,Boleto,NaN
299,300,2025-03-09,PED-1300,Cliente XPTO,Ponta Grossa,PR,Carlos S.,Parafusadeira,Ferramentas,7,2456.845684,17197.919789,0,Muito Insatisfeito,PIX,NaN

In [59]:

dt.Categoria.unique()

<StringArray>
['Medição', 'Ferramentas', 'Soldagem', 'Elétrica']
Length: 4, dtype: str

In [57]:
dt.loc[dt["Produto"] == "Parafusadeira", "Categoria"] = "Ferramentas"

In [60]:
dt.Produto.unique()

<StringArray>
['Soldadora', 'Parafusadeira', 'Furadeira']
Length: 3, dtype: str

In [62]:
dt.loc[dt["Produto"] == "Soldadora"]

,ID_Registro,Data_Pedido,Numero_Pedido,Cliente,Cidade_Cliente,Estado,Vendedor,Produto,Categoria,Quantidade,Valor_Unitario,Valor_Total,Nota_Satisfacao,Comentario_Satisfacao,Forma_Pagamento,Observacao
0,1,2025-02-28,PED-1001,Construtora PR,Cascavel,PR,Carlos S.,Soldadora,Medição,9,4165.28,37487.52,10,Muito Satisfeito,Boleto,NaN
2,3,2025-05-09,PED-1003,Cliente XPTO,Araucária,PR,Carlos S.,Soldadora,Soldagem,12,3067.67,36812.04,10,Muito Satisfeito,Boleto,NaN
8,9,2025-02-12,PED-1009,Cliente XPTO,Araucária,PR,Carlos S.,Soldadora,Ferramentas,4,1963.48,7853.92,0,Muito Insatisfeito,PIX,NaN
16,17,2025-03-25,PED-1017,Construtora PR,Ponta Grossa,PR,Carlos S.,Soldadora,Elétrica,12,1079.75,12957.00,10,Muito Satisfeito,Boleto,NaN
18,19,2025-02-21,PED-1019,Construtora PR,Curitiba,PR,Carlos S.,Soldadora,Soldagem,1,131.84,131.84,10,Muito Satisfeito,Boleto,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274,275,2025-02-24,PED-1275,Oficina Curitiba,Maringá,PR,Carlos S.,Soldadora,Elétrica,10,672.99,6729.90,6,Neutro,Cartão,NaN
281,282,2025-02-17,PED-1282,Oficina Curitiba,Araucária,PR,Carlos S.,Soldadora,Elétrica,29,1995.12,57858.48,0,Muito Insatisfeito,Boleto,NaN
287,288,2025-02-09,PED-1288,Cliente XPTO,Maringá,PR,Carlos S.,Soldadora,Elétrica,14,4273.45,59828.30,0,Muito Insatisfeito,Cartão,NaN
289,290,2025-01-01,PED-1290,Metalúrgica Sul,Curitiba,PR,Carlos S.,Soldadora,Ferramentas,5,1803.81,9019.05,0,Muito Insatisfeito,PIX,NaN
296,297,2025-03-13,PED-1297,Construtora PR,Cascavel,PR,Carlos S.,Soldadora,Elétrica,2,642.54,1285.08,6,Neutro,Boleto,NaN

In [63]:
mediaS = dt.loc[dt["Produto"] == "Soldadora", "Valor_Unitario"].mean()
mediaS

np.float64(2570.3376344086023)

In [66]:
dt.loc[dt["Produto"] == "Soldadora", "Valor_Unitario"] = mediaS

In [71]:
dt.loc[dt["Produto"] == "Soldadora"]

,ID_Registro,Data_Pedido,Numero_Pedido,Cliente,Cidade_Cliente,Estado,Vendedor,Produto,Categoria,Quantidade,Valor_Unitario,Valor_Total,Nota_Satisfacao,Comentario_Satisfacao,Forma_Pagamento,Observacao
0,1,2025-02-28,PED-1001,Construtora PR,Cascavel,PR,Carlos S.,Soldadora,Ferramentas,9,2570.337634,23133.038710,10,Muito Satisfeito,Boleto,NaN
2,3,2025-05-09,PED-1003,Cliente XPTO,Araucária,PR,Carlos S.,Soldadora,Ferramentas,12,2570.337634,30844.051613,10,Muito Satisfeito,Boleto,NaN
8,9,2025-02-12,PED-1009,Cliente XPTO,Araucária,PR,Carlos S.,Soldadora,Ferramentas,4,2570.337634,10281.350538,0,Muito Insatisfeito,PIX,NaN
16,17,2025-03-25,PED-1017,Construtora PR,Ponta Grossa,PR,Carlos S.,Soldadora,Ferramentas,12,2570.337634,30844.051613,10,Muito Satisfeito,Boleto,NaN
18,19,2025-02-21,PED-1019,Construtora PR,Curitiba,PR,Carlos S.,Soldadora,Ferramentas,1,2570.337634,2570.337634,10,Muito Satisfeito,Boleto,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274,275,2025-02-24,PED-1275,Oficina Curitiba,Maringá,PR,Carlos S.,Soldadora,Ferramentas,10,2570.337634,25703.376344,6,Neutro,Cartão,NaN
281,282,2025-02-17,PED-1282,Oficina Curitiba,Araucária,PR,Carlos S.,Soldadora,Ferramentas,29,2570.337634,74539.791398,0,Muito Insatisfeito,Boleto,NaN
287,288,2025-02-09,PED-1288,Cliente XPTO,Maringá,PR,Carlos S.,Soldadora,Ferramentas,14,2570.337634,35984.726882,0,Muito Insatisfeito,Cartão,NaN
289,290,2025-01-01,PED-1290,Metalúrgica Sul,Curitiba,PR,Carlos S.,Soldadora,Ferramentas,5,2570.337634,12851.688172,0,Muito Insatisfeito,PIX,NaN
296,297,2025-03-13,PED-1297,Construtora PR,Cascavel,PR,Carlos S.,Soldadora,Ferramentas,2,2570.337634,5140.675269,6,Neutro,Boleto,NaN

In [70]:
dt.loc[dt["Produto"] == "Soldadora", "Categoria"] = "Ferramentas"

In [72]:
dt.Produto.unique()

<StringArray>
['Soldadora', 'Parafusadeira', 'Furadeira']
Length: 3, dtype: str

In [73]:
dt.loc[dt["Produto"] == "Furadeira"]

,ID_Registro,Data_Pedido,Numero_Pedido,Cliente,Cidade_Cliente,Estado,Vendedor,Produto,Categoria,Quantidade,Valor_Unitario,Valor_Total,Nota_Satisfacao,Comentario_Satisfacao,Forma_Pagamento,Observacao
6,7,2025-05-19,PED-1007,Cliente XPTO,Maringá,PR,Carlos S.,Furadeira,Medição,29,4116.60,119381.40,10,Muito Satisfeito,Boleto,NaN
10,11,2025-01-16,PED-1011,Cliente XPTO,Curitiba,PR,Carlos S.,Furadeira,Ferramentas,3,1687.01,5061.03,10,Muito Satisfeito,Cartão,NaN
12,13,2025-03-11,PED-1013,Construtora PR,Cascavel,PR,Carlos S.,Furadeira,Elétrica,10,2170.15,21701.50,10,Muito Satisfeito,PIX,NaN
19,20,2025-01-30,PED-1020,Construtora PR,Cascavel,PR,Carlos S.,Furadeira,Elétrica,13,930.06,12090.78,10,Muito Satisfeito,Cartão,NaN
23,24,2025-01-17,PED-1024,Cliente XPTO,Araucária,PR,Carlos S.,Furadeira,Elétrica,15,2619.48,39292.20,0,Muito Insatisfeito,Cartão,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,286,2025-01-02,PED-1286,Indústria Alpha,Londrina,PR,Carlos S.,Furadeira,Medição,13,3040.60,39527.80,0,Muito Insatisfeito,Cartão,NaN
286,287,2025-05-15,PED-1287,Indústria Alpha,Londrina,PR,Carlos S.,Furadeira,Ferramentas,8,1571.78,12574.24,6,Neutro,Cartão,NaN
288,289,2025-06-30,PED-1289,Mercado Industrial,Maringá,PR,Carlos S.,Furadeira,Elétrica,6,4127.72,24766.32,0,Muito Insatisfeito,Boleto,NaN
293,294,2025-05-27,PED-1294,Metalúrgica Sul,Maringá,PR,Carlos S.,Furadeira,Ferramentas,3,1756.85,5270.55,10,Muito Satisfeito,Cartão,NaN
295,296,2025-03-29,PED-1296,Loja Ferramentas BR,Curitiba,PR,Carlos S.,Furadeira,Elétrica,14,1543.26,21605.64,0,Muito Insatisfeito,Cartão,NaN

In [74]:
mediaF = dt.loc[dt["Produto"] == "Furadeira", "Valor_Unitario"].mean()
mediaF

np.float64(2619.245535714286)

In [75]:
dt.loc[dt["Produto"] == "Furadeira", "Valor_Unitario"] = mediaF

In [79]:

dt.loc[dt["Produto"] == "Furadeira", "Categoria"] = "Ferramentas"

In [80]:
dt.loc[dt["Produto"] == "Furadeira"]

,ID_Registro,Data_Pedido,Numero_Pedido,Cliente,Cidade_Cliente,Estado,Vendedor,Produto,Categoria,Quantidade,Valor_Unitario,Valor_Total,Nota_Satisfacao,Comentario_Satisfacao,Forma_Pagamento,Observacao
6,7,2025-05-19,PED-1007,Cliente XPTO,Maringá,PR,Carlos S.,Furadeira,Ferramentas,29,2619.245536,75958.120536,10,Muito Satisfeito,Boleto,NaN
10,11,2025-01-16,PED-1011,Cliente XPTO,Curitiba,PR,Carlos S.,Furadeira,Ferramentas,3,2619.245536,7857.736607,10,Muito Satisfeito,Cartão,NaN
12,13,2025-03-11,PED-1013,Construtora PR,Cascavel,PR,Carlos S.,Furadeira,Ferramentas,10,2619.245536,26192.455357,10,Muito Satisfeito,PIX,NaN
19,20,2025-01-30,PED-1020,Construtora PR,Cascavel,PR,Carlos S.,Furadeira,Ferramentas,13,2619.245536,34050.191964,10,Muito Satisfeito,Cartão,NaN
23,24,2025-01-17,PED-1024,Cliente XPTO,Araucária,PR,Carlos S.,Furadeira,Ferramentas,15,2619.245536,39288.683036,0,Muito Insatisfeito,Cartão,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,286,2025-01-02,PED-1286,Indústria Alpha,Londrina,PR,Carlos S.,Furadeira,Ferramentas,13,2619.245536,34050.191964,0,Muito Insatisfeito,Cartão,NaN
286,287,2025-05-15,PED-1287,Indústria Alpha,Londrina,PR,Carlos S.,Furadeira,Ferramentas,8,2619.245536,20953.964286,6,Neutro,Cartão,NaN
288,289,2025-06-30,PED-1289,Mercado Industrial,Maringá,PR,Carlos S.,Furadeira,Ferramentas,6,2619.245536,15715.473214,0,Muito Insatisfeito,Boleto,NaN
293,294,2025-05-27,PED-1294,Metalúrgica Sul,Maringá,PR,Carlos S.,Furadeira,Ferramentas,3,2619.245536,7857.736607,10,Muito Satisfeito,Cartão,NaN
295,296,2025-03-29,PED-1296,Loja Ferramentas BR,Curitiba,PR,Carlos S.,Furadeira,Ferramentas,14,2619.245536,36669.437500,0,Muito Insatisfeito,Cartão,NaN

In [85]:
print(f"{mediaF:.2f}")

2619.25

In [86]:
dt

,ID_Registro,Data_Pedido,Numero_Pedido,Cliente,Cidade_Cliente,Estado,Vendedor,Produto,Categoria,Quantidade,Valor_Unitario,Valor_Total,Nota_Satisfacao,Comentario_Satisfacao,Forma_Pagamento,Observacao
0,1,2025-02-28,PED-1001,Construtora PR,Cascavel,PR,Carlos S.,Soldadora,Ferramentas,9,2570.337634,23133.038710,10,Muito Satisfeito,Boleto,NaN
1,2,2025-01-30,PED-1002,Cliente XPTO,Maringá,PR,Carlos S.,Parafusadeira,Ferramentas,28,2456.845684,68791.679158,10,Muito Satisfeito,PIX,NaN
2,3,2025-05-09,PED-1003,Cliente XPTO,Araucária,PR,Carlos S.,Soldadora,Ferramentas,12,2570.337634,30844.051613,10,Muito Satisfeito,Boleto,NaN
3,4,2025-05-21,PED-1004,Construtora PR,Ponta Grossa,PR,Carlos S.,Parafusadeira,Ferramentas,9,2456.845684,22111.611158,0,Muito Insatisfeito,Cartão,NaN
4,5,2025-03-23,PED-1005,Construtora PR,Maringá,PR,Carlos S.,Parafusadeira,Ferramentas,4,2456.845684,9827.382737,10,Muito Satisfeito,Boleto,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,2025-03-29,PED-1296,Loja Ferramentas BR,Curitiba,PR,Carlos S.,Furadeira,Ferramentas,14,2619.245536,36669.437500,0,Muito Insatisfeito,Cartão,NaN
296,297,2025-03-13,PED-1297,Construtora PR,Cascavel,PR,Carlos S.,Soldadora,Ferramentas,2,2570.337634,5140.675269,6,Neutro,Boleto,NaN
297,298,2025-05-11,PED-1298,Oficina Curitiba,Maringá,PR,Carlos S.,Parafusadeira,Ferramentas,2,2456.845684,4913.691368,10,Muito Satisfeito,Cartão,NaN
298,299,2025-03-17,PED-1299,Mercado Industrial,Curitiba,PR,Carlos S.,Parafusadeira,Ferramentas,1,2456.845684,2456.845684,6,Neutro,Boleto,NaN
299,300,2025-03-09,PED-1300,Cliente XPTO,Ponta Grossa,PR,Carlos S.,Parafusadeira,Ferramentas,7,2456.845684,17197.919789,0,Muito Insatisfeito,PIX,NaN

In [87]:
dt = dt.drop("Comentario_Satisfacao", axis=1)

In [88]:
dt

,ID_Registro,Data_Pedido,Numero_Pedido,Cliente,Cidade_Cliente,Estado,Vendedor,Produto,Categoria,Quantidade,Valor_Unitario,Valor_Total,Nota_Satisfacao,Forma_Pagamento,Observacao
0,1,2025-02-28,PED-1001,Construtora PR,Cascavel,PR,Carlos S.,Soldadora,Ferramentas,9,2570.337634,23133.038710,10,Boleto,NaN
1,2,2025-01-30,PED-1002,Cliente XPTO,Maringá,PR,Carlos S.,Parafusadeira,Ferramentas,28,2456.845684,68791.679158,10,PIX,NaN
2,3,2025-05-09,PED-1003,Cliente XPTO,Araucária,PR,Carlos S.,Soldadora,Ferramentas,12,2570.337634,30844.051613,10,Boleto,NaN
3,4,2025-05-21,PED-1004,Construtora PR,Ponta Grossa,PR,Carlos S.,Parafusadeira,Ferramentas,9,2456.845684,22111.611158,0,Cartão,NaN
4,5,2025-03-23,PED-1005,Construtora PR,Maringá,PR,Carlos S.,Parafusadeira,Ferramentas,4,2456.845684,9827.382737,10,Boleto,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,2025-03-29,PED-1296,Loja Ferramentas BR,Curitiba,PR,Carlos S.,Furadeira,Ferramentas,14,2619.245536,36669.437500,0,Cartão,NaN
296,297,2025-03-13,PED-1297,Construtora PR,Cascavel,PR,Carlos S.,Soldadora,Ferramentas,2,2570.337634,5140.675269,6,Boleto,NaN
297,298,2025-05-11,PED-1298,Oficina Curitiba,Maringá,PR,Carlos S.,Parafusadeira,Ferramentas,2,2456.845684,4913.691368,10,Cartão,NaN
298,299,2025-03-17,PED-1299,Mercado Industrial,Curitiba,PR,Carlos S.,Parafusadeira,Ferramentas,1,2456.845684,2456.845684,6,Boleto,NaN
299,300,2025-03-09,PED-1300,Cliente XPTO,Ponta Grossa,PR,Carlos S.,Parafusadeira,Ferramentas,7,2456.845684,17197.919789,0,PIX,NaN

In [89]:
dt.to_excel("Dados_ComercialPrime_Tratado.xlsx", index=False)